### ISSUE TITLE
Resuming a scheduled Subscription pause raises 400 Error: Bad Request

### ISSUE THREAD

**Issue by archatas** [websideproject/paddle-billing-client#196] opened 2023-12-29 05:24 UTC
## 🐛 Bug Report

Once you pause a subscription with `client.pause_subscription()`, it will be scheduled to pause after the current billing period.

To resume a scheduled pausing, the documentation tells to patch the subscription with `{"scheduled_change": null}`.

However, this fails with the `client.update_subscription()`, because the `SubscriptionRequest(scheduled_change=None)` produces a dictionary with many other parameters like:

```python
{'status': None, 'customer_id': None, 'address_id': None, 'business_id': None, 'currency_code': None, 'created_at': None, 'updated_at': None, 'started_at': None, 'first_billed_at': None, 'next_billed_at': None, 'paused_at': None, 'canceled_at': None, 'collection_mode': None, 'billing_details': None, 'current_billing_period': None, 'billing_cycle': None, 'recurring_transaction_details': None, 'scheduled_change': None, 'items': None, 'custom_data': None, 'management_urls': None, 'discount': None, 'effective_from': None, 'resume_at': None}
```

400 Error: Bad Request is raised.

## 🔬 How To Reproduce

1. Pause a subscription with `effective_from="next_billing_period"`
2. Try to patch it with `client.update_subscription()`

### Code sample

```python
client.pause_subscription(
    subscription_id="sub_xxx",
    data=SubscriptionRequest(
        effective_from="next_billing_period",
    ),
)
client.update_subscription(
    subscription_id="sub_xxx",
    data=SubscriptionRequest(
        scheduled_change=None,
    ),
)
```

Workaround:

```python
client.patch(
    client.endpoints.update_subscription.format(subscription_id="sub_xxx"),
    {"scheduled_change": None},
)
```
### Environment

* OS: macOS
* Python version: 3.10

**Comment by bgervan** [comment] 2023-12-29 06:49
I take a look, at the time of creation the resume returned 500 so I couldn't test it.

**Comment by archatas** [comment] 2023-12-29 06:52
When you try to resume a Subscription which status is still active, you get 500.

Subscriptions which will be cancelled in the future can't be resumed. They need to be patched.

https://developer.paddle.com/build/subscriptions/pause-subscriptions

**Comment by bgervan** [comment] 2023-12-29 07:04
The issue is the Nones are not sent to the server, I need to check how to overcome that. 

None of the below are sent to paddle
`{'status': None, 'customer_id': None, 'address_id': None, 'business_id': None, 'currency_code': None, 'created_at': None, 'updated_at': None, 'started_at': None, 'first_billed_at': None, 'next_billed_at': None, 'paused_at': None, 'canceled_at': None, 'collection_mode': None, 'billing_details': None, 'current_billing_period': None, 'billing_cycle': None, 'recurring_transaction_details': None, 'scheduled_change': None, 'items': None, 'custom_data': None, 'management_urls': None, 'discount': None, 'effective_from': None, 'resume_at': None}
`

**Comment by bgervan** [comment] 2023-12-29 07:11
I am adding a new client function for this, as this is a bit of edge case, they should accept the resume now for this case imo. 

    def unschedule_pause_from_subscription(
        self, subscription_id: str
    ) -> SubscriptionResponse:
        """Remove a scheduled pause from a subscription"""
        return self.patch(
            self.endpoints.update_subscription.format(subscription_id=subscription_id),
            {"scheduled_change": None},
        )

**Comment by archatas** [comment] 2023-12-29 07:13
One other way is to introduce a new class like NOT_PROVIDED from django model fields for the default values. But that might be too much work.

**Comment by bgervan** [comment] 2023-12-29 07:29
I don't see how it would look like, this package is not only for django

**Comment by archatas** [comment] 2023-12-29 07:34
I am talking about the concept of having default values which can be overwritten with values including None.

Something like:

```python
class NOT_PROVIDED:
    pass

class SubscriptionBase(BaseModel):
    status: str | None | NOT_PROVIDED
    ...
```

I am not into Pydantic, so I am not sure about the syntax there.

**Comment by bgervan** [comment] 2023-12-29 07:38
Me neither, for now it is fixed with https://github.com/websideproject/paddle-billing-client/releases/tag/v0.1.17 with this edge case, I will check if pydantic 2 works better for these cases. If the apiclient upgrades to v2, this package can be upgraded too.

> Then if the value is NOT_PROVIDED, it is not sent to the request, if it's None, it is sent.

I am sure it would introduce many issue, it is only possible the other way around, so forcing to include if "NOT_PROVIDED", and in that case, I would name it differently of course

**Comment by archatas** [comment] 2023-12-29 07:41
Thanks for lightning-fast response!

**Comment by bgervan** [comment] 2024-01-06 17:55
It looks resolved with the `def unschedule_pause_from_subscription` function. I am open to PRs if there are any better solution.

**Closed by bgervan** 2024-01-06 17:55 UTC
Labels: bug
